name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # # -name: print out paths
      #  run: |
      #   ls  
      #   echo $GITHUB_SHA
      #   echo $GITHUB_REPOSITORY
      #   echo $GITHUB_WORKSPACE



      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4
       

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 4: Build and run tests
      - name: Build and test
        run: |
          ls  
          mvn clean verify
